// Generate src/shared/logo.js from the master lockup SVG.  node scripts/gen-logo.mjs
// The lockup's first three shapes are the H, B and C of the mark; the last two are the wordmark.
import { readFile, writeFile } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const svg = (await readFile(join(HERE, '../../assets/heartbeat-lockup-white.svg'), 'utf8')).trim();
const shapes = svg.match(/<(polygon|path)[^>]*\/>/g);
if (shapes?.length !== 5) throw new Error(`expected 5 shapes in the lockup, found ${shapes?.length}`);
const tagged = ['H', 'B', 'C'].map((c, i) => shapes[i].replace(/^<(\w+)/, `<$1 class="${c}"`));
const mark = `<g class="mark">${tagged.join('')}</g>`;
const word = `<g class="word">${shapes.slice(3).join('')}</g>`;

const out = `// GENERATED by scripts/gen-logo.mjs from brand/assets/heartbeat-lockup-white.svg. Do not edit.
(function () {
  const HB = (globalThis.HB = globalThis.HB || {});
  const LOGO = HB.LOGO = {
    mark: ${JSON.stringify(mark)},
    word: ${JSON.stringify(word)},
    viewBox: '0 0 252.2 111.27',
    markBox: [0, 0, 93.43, 111.27],
  };
  // opts: { className, label }. Fill follows currentColor; parts keep classes H, B, C, mark, word.
  const attrs = o => \`\${o.className ? \` class="\${o.className}"\` : ''}\${o.label ? \` role="img" aria-label="\${o.label}"\` : ' aria-hidden="true"'}\`;
  HB.lockupSVG = (o = {}) => \`<svg xmlns="http://www.w3.org/2000/svg" viewBox="\${LOGO.viewBox}" fill="currentColor"\${attrs(o)}>\${LOGO.mark}\${LOGO.word}</svg>\`;
  HB.markSVG = (o = {}) => \`<svg xmlns="http://www.w3.org/2000/svg" viewBox="\${LOGO.markBox.join(' ')}" fill="currentColor"\${attrs(o)}>\${LOGO.mark}</svg>\`;
})();
`;
await writeFile(join(HERE, '../src/shared/logo.js'), out);
console.log('wrote src/shared/logo.js');
