apiVersion: v2
name: common
description: Common infrastructure components including Azure Key Vault CSI driver
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: csi-secrets-store-provider-azure
    version: "1.7.0"
    repository: "https://azure.github.io/secrets-store-csi-driver-provider-azure/charts"
