apiVersion: v1
kind: Service
metadata:
  name: website
  namespace: website-dev
  labels:
    app: website
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 2368
    protocol: TCP
    name: http
  selector:
    app: website
