apiVersion: v1
kind: Namespace
metadata:
  name: a-csi-driver
  labels:
    name: a-csi-driver
  annotations:
    description: "Namespace for Azure CSI driver components"
---
apiVersion: v1
kind: Namespace
metadata:
  name: a-workload-identity
  labels:
    name: a-workload-identity
  annotations:
    description: "Namespace for Azure Workload Identity webhook components"
