apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Base resources to include (reference components from base directory)
resources:
- ../../base/webapp
- ../../base/redis

# No global namespace - we'll set per-component
# namespace: heartbeat-dev

# Common labels for dev environment
commonLabels:
  environment: dev
  app.kubernetes.io/environment: dev

# Patches for dev-specific modifications
patches:
# Set different namespaces for each app
- target:
    kind: Deployment
    name: webapp
  patch: |-
    - op: replace
      path: /metadata/namespace
      value: webapp-dev
- target:
    kind: Service
    name: webapp
  patch: |-
    - op: replace
      path: /metadata/namespace
      value: webapp-dev
- target:
    kind: Deployment
    name: redis
  patch: |-
    - op: replace
      path: /metadata/namespace
      value: redis-dev
- target:
    kind: Service
    name: redis
  patch: |-
    - op: replace
      path: /metadata/namespace
      value: redis-dev

# Config map generators for dev-specific config
configMapGenerator:
- name: env-config
  literals:
  - ENVIRONMENT=dev
  - LOG_LEVEL=debug
  - DEBUG=true

# Secret generators (if needed)
# secretGenerator:
# - name: env-secrets
#   literals:
#   - API_KEY=dev-api-key

# Images to override (for using dev/latest tags)
images: []
# Example:
# - name: my-app
#   newTag: latest
#   newName: my-registry.com/my-app

# Replicas for dev (typically lower)
replicas:
# - name: my-app
#   count: 1
