apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Base resources to include (reference components from base directory)
resources:
- ../../base/common
- ../../base/website

# Common labels for dev environment
commonLabels:
  environment: dev
  app.kubernetes.io/environment: dev

# Patches for dev-specific modifications
patches:
# Set namespace for all CSI driver components
- target:
    labelSelector: "app=csi-secrets-store-provider-azure"
  patch: |-
    - op: replace
      path: /metadata/namespace
      value: a-csi-driver
- target:
    labelSelector: "app=secrets-store-csi-driver"
  patch: |-
    - op: replace
      path: /metadata/namespace
      value: a-csi-driver

# Set namespace for workload identity webhook components
- target:
    labelSelector: "app=workload-identity-webhook"
  patch: |-
    - op: replace
      path: /metadata/namespace
      value: a-workload-identity

# Config map generators for dev-specific config
configMapGenerator:
- name: env-config
  literals:
  - ENVIRONMENT=dev
  - LOG_LEVEL=debug
  - DEBUG=true

# Secret generators (if needed)
# secretGenerator:
# - name: env-secrets
#   literals:
#   - API_KEY=dev-api-key

# Images to override (for using dev/latest tags)
images: []
# Example:
# - name: my-app
#   newTag: latest
#   newName: my-registry.com/my-app

# Replicas for dev (typically lower)
replicas:
# - name: my-app
#   count: 1
